vich_uploader:
    db_driver: orm

    mappings:
        category_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        product_image:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        blogs:
            uri_prefix: /uploads/blogs
            upload_destination: '%kernel.project_dir%/public/uploads/blogs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true